name: Manual Profile Updater

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Running Scripts
        run: |
          pip install -r requirements.txt
          python script.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated profile."
          git push